### ISSUE TITLE
¿Y si la presentación está en otro repo?

### ISSUE THREAD

**Issue by JJ** [opensouthcode/2017#6]
¿No será mejor, como dice #2 , subir el programa del evento y que cada cual lo enlace donde se encuentre?

**Comment by davidsf** [comment]
Pues se pueden subir un .md apuntando a donde esté el repo o presentaciones, como han hecho ya: https://github.com/opensouthcode/2017/blob/master/presentaciones/introduccion_a_angular.md

Creo que queda bien ¿ no ?

**Comment by linuxonrails** [comment]
He añadido (en un fork) un listado con enlaces en la portada:

https://github.com/linuxonrails/2017#por-orden-alfabético

...para añadir enlaces a los repositorios correspondientes de las charlas.

**Comment by JJ** [comment]
Genial, gracias.
